### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by alphaolomi** [nextsms/js-client#4]
# Road Map 🗺️ 

0. [x] Make it work
1. [ ] Improve and organise internal code structure ie interfaces,exceptions.
2. [ ] Add documentations
3. [ ] Validate data input using Regex before API call.
4. [ ] Throw respective Exception depending on response status code
